#!/usr/bin/python3

import subprocess
import yaml
import sys
import base64

def get_secret_sections(kube_namespace):
    """ Get all secrets inside the given namespace """
    kube_secrets = subprocess.check_output("kubectl get secret -n "+kube_namespace+" -o yaml", shell=True)
    kube_secrets_data = yaml.load(kube_secrets, Loader=yaml.FullLoader)["items"]
    for i in range(0,len(kube_secrets_data)):
        print ("Secrets Names in \x1b[1;32;40m"+kube_namespace+"\x1b[0m namespace:", kube_secrets_data[i]["metadata"]["name"])

def get_secrets(kube_namespace, kube_secret_name):
    """ Decode the given secret """
    kube_secrets = subprocess.check_output("kubectl get secret -n "+kube_namespace+" -o yaml "+kube_secret_name, shell=True)
    kube_secrets_data = yaml.load(kube_secrets, Loader=yaml.FullLoader)["data"]
    for k,v in kube_secrets_data.items():
        decoded_v = base64.b64decode(v)
        try:
            print ('\x1b[1;32;40m'+k,":\x1b[0m", decoded_v.decode())
        except:
            print ('\x1b[1;31;40mBinary secret: '+k,":\x1b[0m", v)

kube_current_context = subprocess.check_output("kubectl config current-context", shell=True)
print ("\x1b[6;30;42mCurrent kube context is: ", kube_current_context.strip().decode(), '\x1b[0m')

if len(sys.argv) == 2:
    get_secret_sections(sys.argv[1])
elif len(sys.argv) == 3:
    get_secrets(sys.argv[1], sys.argv[2])
else:
    print ("Namespace required. Example: kubedecode <namespace> [<secret_name>]")
    exit(0)
